# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickandmortruser',
            name='lat',
            field=models.FloatField(default=32.7767),
        ),
        migrations.AlterField(
            model_name='brickandmortruser',
            name='lon',
            field=models.FloatField(default=-96.797),
        ),
    ]
