# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170924_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickandmortruser',
            name='bag_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brickandmortruser',
            name='favorites_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
