# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20170928_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickandmortruser',
            name='bag_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='brickandmortruser',
            name='favorites_json',
            field=models.TextField(default='[]'),
        ),
    ]
