# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170928_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickandmortruser',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
