# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20171002_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickandmortruser',
            name='preferences_json',
            field=models.TextField(default='{}'),
        ),
    ]
