# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_brickandmortruser_preferences_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
