# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20171103_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickandmortruser',
            name='password_reset_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brickandmortruser',
            name='password_reset_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
