# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20171107_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 16, 45, 35, 370115)),
        ),
    ]
