# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_item_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 16, 47, 36, 759225)),
        ),
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
