# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20171107_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('sizes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 18, 27, 46, 386998)),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.SubCategory'),
        ),
    ]
