# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20171116_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 18, 48, 22, 439417)),
        ),
    ]
