# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20171116_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 19, 22, 8, 545874)),
        ),
    ]
