# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20171116_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.CharField(choices=[('c', 'clothing'), ('s', 'shoes'), ('b', 'bags'), ('a', 'accessories')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 15, 8, 13, 796074)),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('c', 'clothing'), ('s', 'shoes'), ('b', 'bags'), ('a', 'accessories')], default='c', max_length=1),
        ),
    ]
